### PR TITLE
fix: add integrity to cdn scripts and remove unused

### PR DESCRIPTION
**Pull request by allensquare**
https://sansec.io/research/polyfill-supply-chain-attack

https://www.jsdelivr.com/using-sri-with-dynamic-files

Adding integrity to the jsdelivr scripts.

### CODE REVIEW

**Comment by kchung** [comment]
@allensquare i would suggest using `fix` over `chore` so that it cuts a release and generates a release notes

**Review by kchung — APPROVED** [review]
Thanks!

**Comment by kchung** [comment]
@allensquare ah shoot, the rename should've also been done through the commit as well. I thought it would pick it up from the title but what it does is it scans all the commits and sees what version bump is needed

**Comment by allensquare** [comment]
@kchung  Ahh shoot... I thought it would squash and use title as commit since the button says "Squash and merge". Any re-course or do I just manually create a new release?

**Comment by kchung** [comment]
@allensquare yeah that's what i thought would've happened too but that's not how it works. I did this a few times: https://github.com/square/brisk-theme/pull/53

**Comment by allensquare** [comment]
@kchung https://github.com/square/brisk-theme/pull/67

**Pull request merged**
